version: "3.8"

services:
  # Production build
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "2005:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  react-dev:
    # Development build
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
